# TensorFlow
TensorFlow is an open source library which is used to develop and train Machine Learning/Deep Learning models

### Programming Element of TensorFlow
**Constant:** It is use to create a constant tensor from a tensor-like object.

**Variable:** It allows to add new trainable parameters to the graph. 

**Placeholder:** It allows to feed the data to a TensorFlow model from outside a model. 

**Sparse Tensor:** It enable efficient storage and processing of tensors that contain maximum zero’s values



## How to creae a TensorFlow Constant?
It is use to create a constant tensor from a tensor-like object.

**Syntax:** tf.constant()

There are 4 paramenters of a TensoFlow constant.

value: A constant value (or a list) of output dtype.

dtype: A type of data type (int float boolean)

shape: Optional dimentions of resulting Tensor.

name: Opetional name for the Tensor.



### Important Note:


1.   Most of TensorFlow syntax is similar to Numpy.
2.   While building neural network graph need constant varisable like input data, it never change while training. 
3. We cannot convert Python sequence with mixed typed to Tensor



In [ ]:
import tensorflow as tf
tf.__version__

'2.5.0'

In [ ]:
tf.test.is_gpu_available

<function tensorflow.python.framework.test_util.is_gpu_available>

In [ ]:
# Create Integer Constant 
tf.constant(10)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
# Create Float Constant 
tf.constant(10.05)

<tf.Tensor: shape=(), dtype=float32, numpy=10.05>

In [ ]:
# Create String Constant 
tf.constant("Nasir")

<tf.Tensor: shape=(), dtype=string, numpy=b'Nasir'>

In [ ]:
# Create Float Constant 
tf.constant(True)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Create Constant Numpy Array/List/Tuple
import numpy as np
tf.constant(np.array([1,2,3,4]))

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [ ]:
# Create 1D Constant
oneD_array = tf.constant([1,2,3,4])
print (oneD_array)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
# Create 2D Constant
twoD_array = tf.constant([[1,2,],[3,4]])
print (twoD_array)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
# Create 2D Constant Array Using 1D Array
twoD_array = tf.constant([1,2,3,4], shape = (2,2))
print (twoD_array)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
# Create 2D Constant Array Using 1D Array WIth Data Type
twoD_array = tf.constant([1,2,3,4], shape = (2,2), dtype = "float32")
print (twoD_array)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [ ]:
# Create N-D Constant
ND_array = tf.constant([[[1,2],[2,3],[4,5]]])
print (ND_array)

tf.Tensor(
[[[1 2]
  [2 3]
  [4 5]]], shape=(1, 3, 2), dtype=int32)


In [ ]:
# Type of Constant
type (ND_array)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
# Shape of Constant
ND_array.shape

TensorShape([1, 3, 2])

In [ ]:
# Dtype of Constant
oneD_array.dtype

tf.int32

In [ ]:
# Access Constant Value
oneD_array.numpy()

array([1, 2, 3, 4], dtype=int32)

## How to creae a TensorFlow Varaible?
It allows to add new trainable parameters to the graph(structure of neural network). 

**Syntax:** tf.Variable()

The Variable() constructor requires an initial value for the variable, which can be a Tensor of any **type** and **shape**. This initial value defines the type and shape of the variable. 

After construction, the type and shape of the variable are **fixed**. It means that shape and type will never change. The value can be changed using one of the assign methods. 

While writing a **syntax** of TensorFlow variable the first letter should be capital. 

**Parameter of a TensorFlow Variable:**

tf.Varaible (initial_value=None, trainable=None, validate_shape=True, caching_device=None, name=None, variable_def=None, dtype=None, import_scope=None, constraint=None, synchronization=VariableSynchronization.AUTO, aggregation=VariableAggregation.NONE, shape=None)

In [ ]:
import tensorflow as tf

In [ ]:
# Create Tensor Variable (It Save The Variable Name It Self)
tf.Variable(1)


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [ ]:
# Create Tensor Variable Using Array
var = tf.Variable([1,2,3,4])
print (var)


<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>


In [ ]:
# Access Tensor Variable Value
var.numpy()

array([1, 2, 3, 4], dtype=int32)

In [ ]:
# Create TF using Integer Value
tf_int = tf.Variable([1,2,3,4])
tf_int


<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
# Create TF using Float Value
tf_float = tf.Variable([1.5 ,2.5 ,3.5 ,4.5])
tf_float


<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.5, 2.5, 3.5, 4.5], dtype=float32)>

In [ ]:
# Create TF using String 
tf_str1 = tf.Variable(['N', 'A', 'S', 'I', 'R'])
tf_str1


<tf.Variable 'Variable:0' shape=(5,) dtype=string, numpy=array([b'N', b'A', b'S', b'I', b'R'], dtype=object)>

In [ ]:
# Create TF using Boolean Value
tf_bool = tf.Variable(True)
tf_bool

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [ ]:
# Create TF using Complex Vale
tf_complex = tf.Variable([1+2j])
tf_complex

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([1.+2.j])>

**Create TF Variable From Constant**

In [ ]:
tf_const = tf.constant([1,2,3,4])
tf_const

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.Variable(tf_const)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

**Create TF Variable With Different Shape**

In [ ]:
twoD_array = tf.Variable([[1,2],[3,4]], shape = (2,2), dtype="int32")
twoD_array

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
a = tf.Variable([1,2,3,4])
tf.reshape(a, (2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

**Get Index of Highest Value** 

In [ ]:
twoD_array = tf.Variable([[1,2],[3,4]], shape = (2,2), dtype="int32")
tf.argmax(twoD_array)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [ ]:
# For Only Maximum Index Value We Will Use Given Below Code
tf.argmax(twoD_array).numpy()

array([1, 1])

**Viewed/Convert Variable or Constant into a Tensor**

In [ ]:
num = tf.Variable([1,2,3,4])

In [ ]:
tf.convert_to_tensor(num)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

**Change/Assign A New Value into a Tensor**

In [ ]:
# Type & Shape Will Never Change. So, We Can Only Replace The Given Values
num.assign([4,3,2,1])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 3, 2, 1], dtype=int32)>

**Assign a Variable With Another Memory**

In [ ]:
num.assign_add([4,3,2,1])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([8, 6, 4, 2], dtype=int32)>

## How to creae a TensorFlow Placeholder?
A placeholder is simply a variable that we will assign data to at a later date. It allows us to create our operation and build our computation graph, without needing the data. 
**Syntax:** tf.placeholder(dtype, shape = none, name = none)


In [2]:
import tensorflow as tf 

In [4]:
tf.placeholder(dtype.float32, shape=(400,400))
# it given error becuase tensorflow version 2 does not compatible 

AttributeError: ignored

In [9]:
# Placeholder are not executeable immediately so we need to disable eager execution in TF_2 not in TF_v1
tf.compat.v1.disable_eager_execution()

In [12]:
tf.compat.v1.placeholder(dtype = "float32", shape=(400,400))

<tf.Tensor 'Placeholder:0' shape=(400, 400) dtype=float32>

**Perform Mathmetical Operation With Placeholder**

In [15]:
a = tf.compat.v1.placeholder(dtype = "int32", shape= (400,400))
b = tf.compat.v1.placeholder(dtype = "int32", shape= (400,400))
c = tf.add(a,b)
c


<tf.Tensor 'Add_1:0' shape=(400, 400) dtype=int32>

In [16]:
#Create A Number 
import numpy as np


In [17]:
ones_array = np.ones((400,400), np.int32)
ones_array

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int32)

In [25]:
# Execute Tensorflow Placeholder using session to execute in TF_v1 
with tf.compat.v1.Session() as sess:
  d =sess.run(c, feed_dict = {a:ones_array, b:ones_array})  # To store it anohter varaible to call it
d # to recall 

array([[2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       ...,
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2]], dtype=int32)

## How to creae a TensorFlow SparseTensor?
It enable efficient storage and processing of tensors that contain maximum zero’s values. 

Tensor that contain mostly zero values are called sparse tensor. 

When working with tensors that contain a lot of zero values, it is important to store them in a space-and time-efficient manner. 

Sparse tensors enable efficient storage and processing of tensors that contain a lot of zero values. Sparse tensors are used extensively in encoding schemes like TF-IDF as part of data pre-processing in NLP applications and for pre-processing images with a lot of dark pixels in computer vision applications.

Currently, sparse tensors in TensorFlow are encoded using the coordinate list (C00) format. 

The COO encoding for sparse tensors is comprised of: 

**values:** A ID tensor with shape [N] containing all nonzero values. 

**indices:** A 2D tensor with shape [N, rank], containing the indices of the nonzero values.

**dense_shape:** A 1D tensor with shape [rank], specifying the shape of the tensor. 
lever° value in the context of a tf.SparseTensor is a value that's not explicitly encoded. 

**Syntax:** tf.SparseTensor(dtype, shape = none, name = none)

In [26]:
import tensorflow as tf


In [29]:
tf.SparseTensor(indices=[[1,2],[3,4]], values = [10,20], dense_shape = [3,10] )

In [31]:
a = tf.SparseTensor(indices=[[1,2],[3,4]], values = [10,20], dense_shape = [3,10] )
print(a)

SparseTensor(indices=Tensor("SparseTensor_2/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_2/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_2/dense_shape:0", shape=(2,), dtype=int64))


**Create SparseTense From Dense**

In [46]:
import numpy as np
np_array = np.array ([[0,0,0,0],
                     [0,1,0,0],
                     [0,0,1,0],
                     [0,0,0,1]])
np_array

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [47]:
tf.sparse.from_dense(np_array)

**Extract the Value, Indices, Shape of Sparse Tensor**

In [48]:
stored_tensor = tf.sparse.from_dense(np_array)

In [49]:
print (stored_tensor)

SparseTensor(indices=Tensor("dense_to_sparse_5/Where:0", shape=(None, 2), dtype=int64), values=Tensor("dense_to_sparse_5/GatherNd:0", shape=(None,), dtype=int64), dense_shape=Tensor("dense_to_sparse_5/Shape:0", shape=(2,), dtype=int64))


In [63]:
# Value
stored_tensor.values

<tf.Tensor 'dense_to_sparse_5/GatherNd:0' shape=(None,) dtype=int64>

In [60]:
 # Indices
stored_tensor.indices

<tf.Tensor 'dense_to_sparse_5/Where:0' shape=(None, 2) dtype=int64>

In [61]:
# Shapes
stored_tensor.dense_shape

<tf.Tensor 'dense_to_sparse_5/Shape:0' shape=(2,) dtype=int64>

**Sparse Tensor To Dense**

If most of the elements are nonzero, then the tensor is considered dense.

In [67]:
dt_fst = tf.sparse.to_dense(stored_tensor)
dt_fst

<tf.Tensor 'SparseToDense_3:0' shape=(4, 4) dtype=int64>

**Mathematical Operation on SparseTensor**

In [68]:
import numpy as np
np_array1 = np.array ([[0,0,0,0],
                     [0,1,0,0],
                     [0,0,1,0],
                     [0,0,0,1]])
np_array2 = np.array ([[0,0,0,0],
                     [0,1,0,0],
                     [0,0,1,0],
                     [0,0,0,1]])

In [76]:
c = tf.add (np_array1, np_array2)
c

<tf.Tensor 'Add_6:0' shape=(4, 4) dtype=int64>